package com.kosta136th.scrap;

public class DemesticPopular {
	

	private String DOMESTIC_SCRAP_URL;
	private String DOMESTIC_SCRAP_TITLE;
	private String DOMESTIC_SCRAP_DESCRIPTION;
	private String DOMESTIC_SCRAP_PUBDATE;
	private String DOMESTIC_SCRAP_KEYWORD;
	public String getDOMESTIC_SCRAP_URL() {
		return DOMESTIC_SCRAP_URL;
	}
	public void setDOMESTIC_SCRAP_URL(String dOMESTIC_SCRAP_URL) {
		DOMESTIC_SCRAP_URL = dOMESTIC_SCRAP_URL;
	}
	public String getDOMESTIC_SCRAP_TITLE() {
		return DOMESTIC_SCRAP_TITLE;
	}
	public void setDOMESTIC_SCRAP_TITLE(String dOMESTIC_SCRAP_TITLE) {
		DOMESTIC_SCRAP_TITLE = dOMESTIC_SCRAP_TITLE;
	}
	public String getDOMESTIC_SCRAP_DESCRIPTION() {
		return DOMESTIC_SCRAP_DESCRIPTION;
	}
	public void setDOMESTIC_SCRAP_DESCRIPTION(String dOMESTIC_SCRAP_DESCRIPTION) {
		DOMESTIC_SCRAP_DESCRIPTION = dOMESTIC_SCRAP_DESCRIPTION;
	}
	public String getDOMESTIC_SCRAP_PUBDATE() {
		return DOMESTIC_SCRAP_PUBDATE;
	}
	public void setDOMESTIC_SCRAP_PUBDATE(String dOMESTIC_SCRAP_PUBDATE) {
		DOMESTIC_SCRAP_PUBDATE = dOMESTIC_SCRAP_PUBDATE;
	}
	public String getDOMESTIC_SCRAP_KEYWORD() {
		return DOMESTIC_SCRAP_KEYWORD;
	}
	public void setDOMESTIC_SCRAP_KEYWORD(String dOMESTIC_SCRAP_KEYWORD) {
		DOMESTIC_SCRAP_KEYWORD = dOMESTIC_SCRAP_KEYWORD;
	}
	@Override
	public String toString() {
		return "DemesticPopulor [DOMESTIC_SCRAP_URL=" + DOMESTIC_SCRAP_URL + ", DOMESTIC_SCRAP_TITLE="
				+ DOMESTIC_SCRAP_TITLE + ", DOMESTIC_SCRAP_DESCRIPTION=" + DOMESTIC_SCRAP_DESCRIPTION
				+ ", DOMESTIC_SCRAP_PUBDATE=" + DOMESTIC_SCRAP_PUBDATE + ", DOMESTIC_SCRAP_KEYWORD="
				+ DOMESTIC_SCRAP_KEYWORD + "]";
	}
	
	

}
