create database bitcoin;
USE bitcoin;


DROP TABLE DEALER_NEWS_FILE;
DROP TABLE REPLY;
DROP TABLE DEALER_NEWS;
DROP TABLE DEALER_PHOTO;abroad_scrap
DROP TABLE DEALER_MAIN;
DROP TABLE DEALER_PAGE;
DROP TABLE DOMESTIC_SCRAP;
DROP TABLE ABROAD_SCRAP;
DROP TABLE LOGIN;
DROP TABLE REGISTER_TYPE;
DROP TABLE USER;
DROP TABLE MARKET_PRICE;
DROP TABLE ADMIN_LOGIN;
DROP TABLE ADMIN;
DROP TABLE AUTHORITY; 
DROP TABLE GUEST;


SHOW TAbitcoinadminabroad_scrapBLES;


#관리자 권한 
CREATE TABLE AUTHORITY (


AUTHORITY_NUM INT AUTO_INCREMENT,
AUTHORITY_CODE INT NOT NULL,
PRIMARY KEY(AUTHORITY_NUM)


);


#관리자
CREATE TABLE ADMIN (


ADMIN_NUM INT AUTO_INCREMENT,
ADMIN_ID VARCHAR(20) NOT NULL,
ADMIN_PASSWORD VARCHAR(60) NOT NULL,
AUTHORITY_NUM INT NOT NULL,
ADMIN_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(ADMIN_NUM),
FOREIGN KEY(AUTHORITY_NUM) REFERENCES AUTHORITY(AUTHORITY_NUM) ON UPDATE CASCADE




);


#관리자로그인
CREATE TABLE ADMIN_LOGIN (


LOGIN_NUM INT AUTO_INCREMENT,
ADMIN_NUM INT NOT NULL,
LOGIN_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
LOGOUT_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(LOGIN_NUM),
FOREIGN KEY(ADMIN_NUM) REFERENCES ADMIN(ADMIN_NUM) ON UPDATE CASCADE


);


#비회원
CREATE TABLE GUEST (


GUEST_NUM INT AUTO_INCREMENT,
GUEST_EMAIL VARCHAR(20) NOT NULL,
PRIMARY KEY(GUEST_NUM)


);


#시세 테이블
CREATE TABLE MARKET_PRICE (


MARKET_PRICE_NUM INT,
LABLE VARCHAR(20) NOT NULL,
NAME VARCHAR(20) NOT NULL,
PRICE_BTC DOUBLE NOT NULL,
PRICE_USD DOUBLE NOT NULL,
PRICE_CNY DOUBLE NOT NULL,
PRICE_EUR DOUBLE NOT NULL,
PRICE_GBP DOUBLE NOT NULL,
PRICE_RUR DOUBLE NOT NULL,
VOLUME DOUBLE NOT NULL,
TIMESTAMP VARCHAR(20) NOT NULL,
PRIMARY KEY(MARKET_PRICE_NUM)


);


#회원
CREATE TABLE USER (


USER_NUM INT AUTO_INCREMENT,
USER_EMAIL VARCHAR(20) NOT NULL,
USER_PASSWORD VARCHAR(60) NOT NULL,
USER_NICKNAME VARCHAR(20) NOT NULL,
USER_SUBSCRIBE_GB VARCHAR(1) DEFAULT 'Y' NOT NULL,
USER_REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(USER_NUM)


);


#가입유형
CREATE TABLE REGISTER_TYPE (


REGISTER_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
REGISTER_TYPE_CODE VARCHAR(1) NOT NULL,
PRIMARY KEY(REGISTER_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#로그인
CREATE TABLE LOGIN (


LOGIN_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
LOGIN_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
LOGOUT_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(LOGIN_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


# 국내스크랩
CREATE TABLE DOMESTIC_SCRAP (


DOMSETIC_SCRAP_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
DOMSETIC_SCRAP_URL VARCHAR(500) NOT NULL,
DOMSETIC_SCRAP_TITLE VARCHAR(300) NOT NULL,
DOMESTIC_SCRAP_DESCRIPTION VARCHAR(1000) NOT NULL,
DOMESTIC_SCRAP_PUBDATE VARCHAR(50) NOT NULL,
DOMESTIC_SCRAP_KEYWORD VARCHAR(50) NOT NULL,
PRIMARY KEY(DOMSETIC_SCRAP_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#해외스크랩
CREATE TABLE ABROAD_SCRAP (


ABROAD_SCRAP_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
ABROAD_SCRAP_URL VARCHAR(500) NOT NULL,
ABROAD_SCRAP_TITLE VARCHAR(300) NOT NULL,
ABROAD_SCRAP_DESCRIPTION VARCHAR(1000) NOT NULL,
ABROAD_SCRAP_PUBDATE VARCHAR(50) NOT NULL,
ABROAD_SCRAP_IMG_URL VARCHAR(500) NOT NULL,
ABROAD_SCRAP_WRITER VARCHAR(50) NOT NULL,
PRIMARY KEY(ABROAD_SCRAP_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);




#딜러페이지
CREATE TABLE DEALER_PAGE (


DEALER_PAGE_NUM INT,
USER_NUM INT NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
LIKE_COUNT INT NOT NULL DEFAULT 0,
DISLIKE_COUNT INT NOT NULL DEFAULT 0,
PRIMARY KEY(DEALER_PAGE_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#딜러사진
CREATE TABLE DEALER_PHOTO (


DEALER_PHOTO_NUM INT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NUM VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_PHOTO_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#딜러메인
CREATE TABLE DEALER_MAIN (


DEALER_MAIN_NUM INT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NUM VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_MAIN_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#전문소식
CREATE TABLE DEALER_NEWS (


DEALER_NEWS_NUM INT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
TITLE VARCHAR(50) NOT NULL,
CONTENT VARCHAR(3000) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
PRIMARY KEY(DEALER_NEWS_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#댓글
CREATE TABLE REPLY (


REPLY_NUM INT,
DEALER_NEWS_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
CONTENT VARCHAR(1500) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
PRIMARY KEY(REPLY_NUM),
FOREIGN KEY(DEALER_NEWS_NUM) REFERENCES DEALER_NEWS(DEALER_NEWS_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE


);


#W전문소식 첨부파일
CREATE TABLE DEALER_NEWS_FILE (


DEALER_NEWS_FILE_NUM INT,
DEALER_NEWS_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NUM VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_NEWS_FILE_NUM),
FOREIGN KEY(DEALER_NEWS_NUM) REFERENCES DEALER_NEWS(DEALER_NEWS_NUM) ON UPDATE CASCADE


);




COMMIT;