create database bitcoin;
USE bitcoin;

DROP TABLE DEALER_NEWS_FILE;
DROP TABLE REPLY;
DROP TABLE DEALER_NEWS;
DROP TABLE DEALER_PHOTO;
DROP TABLE DEALER_MAIN;
DROP TABLE DEALER_PAGE;
DROP TABLE DOMESTIC_SCRAP;
DROP TABLE ABROAD_SCRAP;
DROP TABLE LOGIN;
DROP TABLE REGISTER_TYPE;
DROP TABLE USER;
DROP TABLE MARKET_PRICE;
DROP TABLE ADMIN_LOGIN;
DROP TABLE ADMIN;
DROP TABLE AUTHORITY; 
DROP TABLE GUEST;

SHOW TABLES;


#관리자 권한 
CREATE TABLE AUTHORITY (

AUTHORITY_NUM INT AUTO_INCREMENT,
AUTHORITY_CODE INT NOT NULL,
PRIMARY KEY(AUTHORITY_NUM)

);

#관리자
CREATE TABLE ADMIN (

ADMIN_NUM INT AUTO_INCREMENT,
ADMIN_ID VARCHAR(20) NOT NULL,
ADMIN_PASSWORD VARCHAR(60) NOT NULL,
AUTHORITY_NUM INT NOT NULL,
ADMIN_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY(ADMIN_NUM),
FOREIGN KEY(AUTHORITY_NUM) REFERENCES AUTHORITY(AUTHORITY_NUM) ON UPDATE CASCADE


);

#관리자로그인
CREATE TABLE ADMIN_LOGIN (

LOGIN_NUM INT AUTO_INCREMENT,
ADMIN_NUM INT NOT NULL,
LOGIN_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
LOGOUT_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(LOGIN_NUM),
FOREIGN KEY(ADMIN_NUM) REFERENCES ADMIN(ADMIN_NUM) ON UPDATE CASCADE

);

#비회원
CREATE TABLE GUEST (

GUEST_NUM INT AUTO_INCREMENT,
GUEST_EMAIL VARCHAR(20) NOT NULL,
PRIMARY KEY(GUEST_NUM)

);

#시세 테이블
CREATE TABLE MARKET_PRICE (

MARKET_PRICE_NUM INT AUTO_INCREMENT ,
LABLE VARCHAR(20) NOT NULL,
NAME VARCHAR(20) NOT NULL,
PRICE_BTC DOUBLE NOT NULL,
PRICE_USD DOUBLE NOT NULL,
PRICE_CNY DOUBLE NOT NULL,
PRICE_EUR DOUBLE NOT NULL,
PRICE_GBP DOUBLE NOT NULL,
PRICE_RUR DOUBLE NOT NULL,
VOLUME DOUBLE NOT NULL,
TIMESTAMP VARCHAR(20) NOT NULL,
PRIMARY KEY(MARKET_PRICE_NUM)

);

#회원
CREATE TABLE USER (

USER_NUM INT AUTO_INCREMENT,
USER_EMAIL VARCHAR(20) NOT NULL,
USER_PASSWORD VARCHAR(60) NOT NULL,
USER_NICKNAME VARCHAR(20) NOT NULL,
USER_SUBSCRIBE_GB VARCHAR(1) DEFAULT 'Y' NOT NULL,
USER_REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(USER_NUM)

);

#가입유형
CREATE TABLE REGISTER_TYPE (

REGISTER_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
REGISTER_TYPE_CODE VARCHAR(1) NOT NULL,
PRIMARY KEY(REGISTER_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#로그인
CREATE TABLE LOGIN (

LOGIN_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
LOGIN_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
LOGOUT_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(LOGIN_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

# 국내스크랩
CREATE TABLE DOMESTIC_SCRAP (

DOMESTIC_SCRAP_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
DOMESTIC_SCRAP_URL VARCHAR(500) NOT NULL,
DOMESTIC_SCRAP_TITLE VARCHAR(300) NOT NULL,
DOMESTIC_SCRAP_DESCRIPTION VARCHAR(1000) NOT NULL,
DOMESTIC_SCRAP_PUBDATE VARCHAR(50) NOT NULL,
DOMESTIC_SCRAP_KEYWORD VARCHAR(50) NOT NULL,
PRIMARY KEY(DOMESTIC_SCRAP_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#해외스크랩
CREATE TABLE ABROAD_SCRAP (

ABROAD_SCRAP_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
ABROAD_SCRAP_URL VARCHAR(500) NOT NULL,
ABROAD_SCRAP_TITLE VARCHAR(300) NOT NULL,
ABROAD_SCRAP_DESCRIPTION VARCHAR(1000) NOT NULL,
ABROAD_SCRAP_PUBDATE VARCHAR(50) NOT NULL,
ABROAD_SCRAP_IMG_URL VARCHAR(500) NOT NULL,
ABROAD_SCRAP_WRITER VARCHAR(50) NOT NULL,
PRIMARY KEY(ABROAD_SCRAP_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#딜러페이지
CREATE TABLE DEALER_PAGE (

DEALER_PAGE_NUM INT AUTO_INCREMENT,
USER_NUM INT NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
LIKE_COUNT INT NOT NULL DEFAULT 0,
DISLIKE_COUNT INT NOT NULL DEFAULT 0,
PRIMARY KEY(DEALER_PAGE_NUM),
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#딜러사진
CREATE TABLE DEALER_PHOTO (

DEALER_PHOTO_NUM INT AUTO_INCREMENT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NAME VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_PHOTO_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#딜러메인
CREATE TABLE DEALER_MAIN (

DEALER_MAIN_NUM INT AUTO_INCREMENT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NAME VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_MAIN_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#전문소식
CREATE TABLE DEALER_NEWS (

DEALER_NEWS_NUM INT AUTO_INCREMENT,
DEALER_PAGE_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
TITLE VARCHAR(50) NOT NULL,
CONTENT VARCHAR(3000) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
PRIMARY KEY(DEALER_NEWS_NUM),
FOREIGN KEY(DEALER_PAGE_NUM) REFERENCES DEALER_PAGE(DEALER_PAGE_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#댓글
CREATE TABLE REPLY (

REPLY_NUM INT AUTO_INCREMENT,
DEALER_NEWS_NUM INT NOT NULL,
USER_NUM INT NOT NULL,
CONTENT VARCHAR(1500) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
DEL_GB VARCHAR(1) DEFAULT 'N' NOT NULL,
PRIMARY KEY(REPLY_NUM),
FOREIGN KEY(DEALER_NEWS_NUM) REFERENCES DEALER_NEWS(DEALER_NEWS_NUM) ON UPDATE CASCADE,
FOREIGN KEY(USER_NUM) REFERENCES USER(USER_NUM) ON UPDATE CASCADE

);

#W전문소식 첨부파일
CREATE TABLE DEALER_NEWS_FILE (

DEALER_NEWS_FILE_NUM INT AUTO_INCREMENT,
DEALER_NEWS_NUM INT NOT NULL,
ORIGINAL_FILE_NAME VARCHAR(50) NOT NULL,
STORED_FILE_NAME VARCHAR(50) NOT NULL,
REGI_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
PRIMARY KEY(DEALER_NEWS_FILE_NUM),
FOREIGN KEY(DEALER_NEWS_NUM) REFERENCES DEALER_NEWS(DEALER_NEWS_NUM) ON UPDATE CASCADE

);



#권한더미
INSERT INTO AUTHORITY(AUTHORITY_CODE) VALUES(1);
INSERT INTO AUTHORITY(AUTHORITY_CODE) VALUES(2);
INSERT INTO AUTHORITY(AUTHORITY_CODE) VALUES(3);

SELECT * FROM AUTHORITY;

#관리자더미
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PASSWORD, AUTHORITY_NUM, ADMIN_NAME) VALUES('ASDF', 1234, 1, 'TONY STARK');
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PASSWORD, AUTHORITY_NUM, ADMIN_NAME) VALUES('QWER', 1234, 2, 'STEVE RODEGERS');
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PASSWORD, AUTHORITY_NUM, ADMIN_NAME) VALUES('ZXCV', 1234, 3, 'BROOS WAYNE');
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PASSWORD, AUTHORITY_NUM, ADMIN_NAME) VALUES('SDFG', 1234, 3, '조현우');
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PASSWORD, AUTHORITY_NUM, ADMIN_NAME) VALUES('QAWS', 1234, 3, '비둘기');

SELECT * FROM ADMIN;

#관리자로그인 더미
INSERT INTO ADMIN_LOGIN(ADMIN_NUM, LOGIN_DATE, LOGOUT_DATE) VALUES(1, NOW(), NOW());
INSERT INTO ADMIN_LOGIN(ADMIN_NUM, LOGIN_DATE, LOGOUT_DATE) VALUES(2, NOW(), NOW());
INSERT INTO ADMIN_LOGIN(ADMIN_NUM, LOGIN_DATE, LOGOUT_DATE) VALUES(3, NOW(), NOW());
INSERT INTO ADMIN_LOGIN(ADMIN_NUM, LOGIN_DATE, LOGOUT_DATE) VALUES(4, NOW(), NOW());
INSERT INTO ADMIN_LOGIN(ADMIN_NUM, LOGIN_DATE, LOGOUT_DATE) VALUES(5, NOW(), NOW());

SELECT * FROM ADMIN_LOGIN;

#비회원 더미
INSERT INTO GUEST(GUEST_EMAIL) VALUES('ASDF@NAVER.COM');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('ASDF@GMAIL.COM');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('ASDF@HANMAIL.NET');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('QWER@NAVER.COM');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('QWER@GMAIL.COM');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('QWER@NHANMAIL.NET');
INSERT INTO GUEST(GUEST_EMAIL) VALUES('ZXCV@NAVER.COM');

SELECT * FROM GUEST;

# 시세 더미
INSERT INTO MARKET_PRICE(LABLE, NAME, PRICE_BTC, PRICE_USD, PRICE_CNY, PRICE_EUR, PRICE_GBP, PRICE_RUR, VOLUME, TIMESTAMP) VALUES('GUGU', 'PSY', 1 , 0.1,  0.2, 0.3, 0.4, 0.5, 100, '141212');

SELECT * FROM MARKET_PRICE;
ALTER TABLE MARKET_PRICE MODIFY MARKET_PRICE_NUM INT AUTO_INCREMENT;

# 회원 더미
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('ABCD@NAVER.COM', 'QWER1234!', 'IRON_MAN');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('QWER@NAVER.COM', 'QWER1234!', 'THOR');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('1234@NAVER.COM', 'QWER1234!', 'BATMAN');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('ZXCV@NAVER.COM', 'QWER1234!', 'SUPERMAN');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('4321@NAVER.COM', 'QWER1234!', 'GUGU');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('POIU@GMAIL.COM', 'QWER1234!', 'WHAT');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('9999@GMAIL.COM', 'QWER1234!', 'OBAMA');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('1111@GMAIL.COM', 'QWER1234!', 'GOOD');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('2222@GMAIL.COM', 'QWER1234!', 'WIDOW');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('3333@GMAIL.COM', 'QWER1234!', 'WINDOW');
#딜러더미
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER1@GMAIL.COM', 'QWER1234!', 'DEALER1');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER2@GMAIL.COM', 'QWER1234!', 'DEALER2');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER3@GMAIL.COM', 'QWER1234!', 'DEALER3');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER4@GMAIL.COM', 'QWER1234!', 'DEALER4');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER5@GMAIL.COM', 'QWER1234!', 'DEALER5');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER6@GMAIL.COM', 'QWER1234!', 'DEALER6');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER7@GMAIL.COM', 'QWER1234!', 'DEALER7');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER8@GMAIL.COM', 'QWER1234!', 'DEALER8');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER9@GMAIL.COM', 'QWER1234!', 'DEALER9');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER10@GMAIL.COM', 'QWER1234!', 'DEALER10');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER11@GMAIL.COM', 'QWER1234!', 'DEALER11');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER12@GMAIL.COM', 'QWER1234!', 'DEALER12');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER13@GMAIL.COM', 'QWER1234!', 'DEALER13');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER14@GMAIL.COM', 'QWER1234!', 'DEALER14');
INSERT INTO USER(USER_EMAIL, USER_PASSWORD, USER_NICKNAME) VALUES('DEALER15@GMAIL.COM', 'QWER1234!', 'DEALER15');


SELECT * FROM USER;
DELETE FROM USER WHERE USER_NUM >4;

#가입유형 더미
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(1, 'N');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(2, 'N');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(3, 'N');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(4, 'N');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(5, 'N');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(6, 'H');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(7, 'H');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(8, 'H');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(9, 'H');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(10, 'H');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(11, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(12, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(13, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(14, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(15, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(16, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(17, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(18, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(19, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(20, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(21, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(22, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(23, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(24, 'D');
INSERT INTO REGISTER_TYPE(USER_NUM, REGISTER_TYPE_CODE) VALUES(25, 'D');

#로그인 더미

INSERT INTO LOGIN(USER_NUM) VALUES(1);
INSERT INTO LOGIN(USER_NUM) VALUES(2);
INSERT INTO LOGIN(USER_NUM) VALUES(3);
INSERT INTO LOGIN(USER_NUM) VALUES(4);
INSERT INTO LOGIN(USER_NUM) VALUES(5);
INSERT INTO LOGIN(USER_NUM) VALUES(6);
INSERT INTO LOGIN(USER_NUM) VALUES(7);
INSERT INTO LOGIN(USER_NUM) VALUES(8);
INSERT INTO LOGIN(USER_NUM) VALUES(9);
INSERT INTO LOGIN(USER_NUM) VALUES(10);

SELECT * FROM LOGIN;

#국내 스크랩 더미
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(1,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 

INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 
INSERT INTO DOMESTIC_SCRAP(USER_NUM, DOMESTIC_SCRAP_URL, DOMESTIC_SCRAP_TITLE, DOMESTIC_SCRAP_DESCRIPTION, DOMESTIC_SCRAP_PUBDATE, DOMESTIC_SCRAP_KEYWORD)
VALUES(2,'WWW.NAVER.COM', 'NAVER', '네이년', '161215', '구라'); 

SELECT * FROM DOMESTIC_SCRAP;

#해외 스크랩 더미
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(1, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');

INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');
INSERT INTO ABROAD_SCRAP(USER_NUM, ABROAD_SCRAP_URL, ABROAD_SCRAP_TITLE, ABROAD_SCRAP_DESCRIPTION, ABROAD_SCRAP_PUBDATE, ABROAD_SCRAP_IMG_URL, ABROAD_SCRAP_WRITER)
VALUES(2, 'WWW.GOOGLE.COM', 'GOOGLE', 'ANDROID', '161211', 'WWW.GOOGLE.COM/IMG', 'GUGU');

SELECT * FROM ABROAD_SCRAP;
#딜러페이지 더미
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(11, '이것이 비트코인이다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(12, '비트코인이 궁금하다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(13, '박근혜 누가 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(14, '이것이 진짜 비트코인이다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(15, '비트코인이 진짜 궁금하다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(16, '박근혜 왜 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(17, '이것이 정말 비트코인이다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(18, '비트코인이 정말 궁금하다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(19, '박근혜 털 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(20, '이것이 레알 비트코인이다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(21, '비트코인이 레알 궁금하다');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(22, '박근혜 머리털 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(23, '박근혜 이빨 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(24, '박근혜 카드 뽑았냐');
INSERT INTO DEALER_PAGE(USER_NUM, CATEGORY) VALUES(25, '박근혜 경북이 뽑았냐');

SELECT * FROM DEALER_PAGE;

#딜러 사진
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(1, 11, '내얼굴', 'ASDGASG');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(2, 12, '내얼굴', 'ZCXBZCB');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(3, 13, '내얼굴', 'ASDGF');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(4, 14, '내얼굴', 'ERFDXAGFA');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(5, 15, '내얼굴', 'XCVBX');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(6, 16, '내얼굴', 'DFGSDFG');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(7, 17, '내얼굴', 'XCVBSDF');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(8, 18, '내얼굴', 'AS23RF');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(9, 19, '내얼굴', 'VCXB34');
INSERT INTO DEALER_PHOTO(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(10, 20, '내얼굴', 'CVXBSDF');

#딜러 메인 
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(1, 11, '내대문', 'ASDGASG');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(2, 12, '내대문', 'XVCBSRG');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(3, 13, '내대문', 'ERGT435T');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(4, 14, '내대문', 'VCXB354');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(5, 15, '내대문', '234GV ');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(6, 16, '내대문', 'VCXN5');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(7, 17, '내대문', 'ASDG46TFG43Q2ASG');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(8, 18, '내대문', 'ASDGDSFHSDASG');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(9, 19, '내대문', 'ASDGA235SG');
INSERT INTO DEALER_MAIN(DEALER_PAGE_NUM, USER_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(10, 20, '내대문', 'ASDGCXVNBASG');

SELECT * FROM DEALER_MAIN;

#전문소식 더미
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 제발 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 정말 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 레알 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 진짜 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 제발 좀먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 절대 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 시밤 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 확실히 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 제발좀 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(1, 11, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');

INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');
INSERT INTO DEALER_NEWS(DEALER_PAGE_NUM, USER_NUM, TITLE, CONTENT) VALUES(2, 12, '비둘기에게 먹이를 주지마세요', '비둘기 박멸');

SELECT * FROM DEALER_NEWS;

#댓글 더미
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 1, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 1, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 2, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 3, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 4, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 5, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 6, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 7, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 8, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 9, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 10, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(1, 11, '비둘기 그켬');

INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 1, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 1, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 2, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 3, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 4, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 5, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 6, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 7, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 8, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 9, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 10, '비둘기 그켬');
INSERT INTO REPLY(DEALER_NEWS_NUM, USER_NUM, CONTENT) VALUES(2, 11, '비둘기 그켬');

SELECT * FROM REPLY;

#전문소식 더미
INSERT INTO DEALER_NEWS_FILE(DEALER_NEWS_NUM, ORIGINAL_FILE_NAME, STORED_FILE_NAME) VALUES(1, 'GUGUGU', 'ZXG890723U');




COMMIT;



